### ISSUE TITLE
导出不了PDF

### ISSUE THREAD

**Issue by cuiziwei** [TooBug/TooNote#3]
0.2.0版本

**Comment by TooBug** [comment]
有详细一点的信息吗？
是从官网下载的mac版吗？有弹出选择保存pdf的文件框吗？有生成一个临时的html文件吗？

**Comment by zhaochunqi** [comment]
同样的问题，从微云下载的版本。没有生成临时html文件，有弹出文件框，但是跟倒出html的文件框并不一致。

**Comment by TooBug** [comment]
@zhaochunqi 麻烦你开一下调试工具，看看有没有什么错误。

具体方法，右键TooNote.app，显示包内容，然后进入`Contents/Resources/app`，打开`electron.js`，将第28行改为`if(1){`，然后再试一下看看有没有什么报错。
