### ISSUE TITLE
vue devtool

### ISSUE THREAD

**Issue by sumshare** [TooBug/TooNote#43]
electron-devtools-installer中工具版本太低
[参考BrowserWindow.addDevToolsExtension](https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md)

**Comment by TooBug** [comment]
好的。晚点看看。

**Comment by TooBug** [comment]
@sumshare 怎么查看devtool的版本呢？还有不同版本有什么区别？我试了一下好像目前调试还是ok的。

**Comment by sumshare** [comment]
@TooBug  之前一直打不开Vue-devtool，现在试了发现几种方法都可以了。
