### ISSUE TITLE
停留在登录页面无响应

### ISSUE THREAD

**Issue by rockjins** [TooBug/TooNote#47]
一直停留在重定向登录的页面，似乎是重定向失败了，但是我可以访问你们的官网，不知道什么原因。
![image](https://cloud.githubusercontent.com/assets/17586155/26401934/b735bc68-40ba-11e7-8c44-528f08c7411d.png)

**Comment by TooBug** [comment]
请问用的是什么版本？是必现吗？你的网络访问github.com是否顺畅？

**Comment by TooBug** [comment]
先关闭了，如果仍有问题，欢迎再次打开并提供更多信息。
