### ISSUE TITLE
Markdown的<del>删除语法不支持

### ISSUE THREAD

**Issue by Keystion** [TooBug/TooNote#5]
版本 0.2.0 (0.2.0)

![image](https://cloud.githubusercontent.com/assets/2408287/21748121/4125e20a-d5b7-11e6-905f-bf6f1f55629e.png)

期望：<del>这是一个删除的tags</del>

**Comment by TooBug** [comment]
嗯。没打开html的支持。晚点支持一下。

**Comment by TooBug** [comment]
可以通过`~~tags~~`实现哦。

**Comment by Keystion** [comment]
get ✔️
