### ISSUE TITLE
是否可以更新下，打包个 windows 版本

### ISSUE THREAD

**Issue by byends** [TooBug/TooNote#6]
1、package.json 里全是只限定了主版本号的包，安装下来，编译各种报错  
2、electron 也没指定版本，使用 electron-packager 打包时只能随便指定一个版本。。  

结果就是：在 win10 下打包失败，麻烦更新下呗

**Comment by TooBug** [comment]
1. 应该只是webpack loader不兼容，试下把webpack.config.js的loader名称补全看看。如果有其他错误可以贴上来看看。
2. 随便指定一个版本一般也没啥问题……这里回头我再研究下，谢谢提醒。


原始邮件
发件人:羽飞notifications@github.com
收件人:TooBug/TooNoteTooNote@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年3月14日(周二) 15:14
主题:[TooBug/TooNote] 是否可以更新下，打包个 windows 版本 (#6)


1、package.json 里全是只限定了主版本号的包，安装下来，编译各种报错
 2、electron 也没指定版本，使用 electron-packager 打包时只能随便指定一个版本。。
结果就是：在 win10 下打包失败，麻烦更新下呗

**Comment by byends** [comment]
嗯，loder 补全以后，报如下BUG：
```
ERROR in ./~/.9.9.5@vue-loader/lib/template-compiler.js?id=data-v-ff6d05ee!./~/.9.9.5@vue-loader/lib/selector.js?type=template&index=0!./component/versions.vue
template syntax error tag <ul> has no matching end tag.
 @ ./component/versions.vue 11:23-148
 @ ./component/app.js
 @ ./main.js
 @ multi ./main.js
```

看到 `component/versions.vue` 里， Line 99  `ul`  应该改为 `transition-group` 吧

**Comment by byends** [comment]
由于 node_modules 太深太多文件，windows 下打包内存溢出了
我试着 把需要打包的文件拎出来到一个目录，结果发现少了一个目录。。。`commonjs`

不知道 `webpack.config.js` 这里的用意是啥？是因为你自己有公共常用库？

```
npmModules.forEach(function(npmModule){
	if(npmModule === 'vue'){
		externals[npmModule] = 'commonjs ' + npmModule + '/dist/vue.js';
		return;
	}
	externals[npmModule] = 'commonjs ' + npmModule;
});
```

**Comment by TooBug** [comment]
这个地方是externals的一个特殊用法，加commonjs前缀后，文件不会被webpack打包进去，而是保留一个require语句。注意commonjs后接的是空格，不是斜杠，所以不是目录。


这里代码会再整理一下，最近在持续弄云服务，预计4月中下旬会出windows版本的。


原始邮件
发件人:羽飞notifications@github.com
收件人:TooBug/TooNoteTooNote@noreply.github.com
抄送:TooBugi@toobug.net; Commentcomment@noreply.github.com
发送时间:2017年3月14日(周二) 18:06
主题:Re: [TooBug/TooNote] 是否可以更新下，打包个 windows 版本 (#6)


由于 node_modules 太深太多文件，windows 下打包内存溢出了
 我试着 把需要打包的文件拎出来到一个目录，结果发现少了一个目录。。。commonjs
不知道 webpack.config.js 这里的用意是啥？是因为你自己有公共常用库？
npmModules.forEach(function(npmModule){ if(npmModule === 'vue'){ externals[npmModule] = 'commonjs ' + npmModule + '/dist/vue.js'; return; } externals[npmModule] = 'commonjs ' + npmModule; });

**Comment by TooBug** [comment]
已提供windows测试版，欢迎试用。<https://toonote.113.im>

注：非正式版本，调试开关未关，还有待优化的地方。
